name: Test Run
favicon: null
layout_spectrum: 0.7534322650171816
typography_spectrum: 0.3964890295173973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1690596779808402
  lightness: 0.2000259852502495
  saturation: 0.870195824187249
  rhythmicContrast: 0.10124977771192789
purpose: []
